/**
 * Implementation of the radial grid.
 */

#include <algorithm>
#include <vector>
#include "FVM/Grid/RadialGrid.hpp"
#include "FVM/Grid/RadialGridGenerator.hpp"
#include "gsl/gsl_integration.h"


using namespace std;
using namespace DREAM::FVM;

/***********************
 * Constructors        *
 ***********************/
/**
 * Initialize an empty grid by only specifying the
 * grid size.
 *
 * rg: Object to use for (re-)generating the radial grid.
 * t0: Time to initialize grid at.
 * ntheta_interp: Poloidal angle resolution in quadrature for flux surface and bounce averages.
 */
RadialGrid::RadialGrid(RadialGridGenerator *rg, const real_t /*t0*/)
    : nr(rg->GetNr()), generator(rg) {

    // Build radial grid for the first time using
    // the given RadialGridGenerator
    // rg->Rebuild(t0, this);

    bool geometryIsSymmetric = rg->IsFieldSymmetric();
    len_t ntheta_interp_passing = rg->GetNthetaInterp();
    FluxSurfaceAverager::interp_method im = FluxSurfaceAverager::INTERP_LINEAR;
    FluxSurfaceAverager::quadrature_method qm_passing = FluxSurfaceAverager::QUAD_FIXED_LEGENDRE;
    fluxSurfaceAverager = new FluxSurfaceAverager(this,geometryIsSymmetric,ntheta_interp_passing,im,qm_passing);
}

/**
 * Destructor.
 */
RadialGrid::~RadialGrid() {
    //DeallocateMagneticField();
    
    
    DeallocateGrid();
    DeallocateFSAvg();

    DeallocateMagneticData();
    
    if(this->VpVol!=nullptr){
        delete [] this->VpVol;
        delete [] this->VpVol_f;
    }
    delete this->generator;
    delete this->fluxSurfaceAverager;
}

/***************************
 * PUBLIC METHODS          *
 ***************************/
/**
 * Rebuilds any non-static (i.e. time dependent) grids
 * used. This can be used if, for example, a dynamically
 * evolving magnetic equilibrium is used, or if some
 * grids are adaptive.
 *
 * t: Time to which re-build the grids for.
 */
bool RadialGrid::Rebuild(const real_t t) {
    // Re-build radial grid
    if (this->generator->NeedsRebuild(t)){
        bool rebuilt = this->generator->Rebuild(t, this);
        return rebuilt;
    }
    else return false;
}

void RadialGrid::RebuildJacobians(){ 
    this->generator->RebuildJacobians(this);
    fluxSurfaceAverager->Rebuild();
    RebuildFluxSurfaceAveragedQuantities();
}


real_t RadialGrid::CalculateFluxSurfaceAverage(len_t ir, fluxGridType fluxGridType, std::function<real_t(real_t,real_t,real_t)> F){
    return fluxSurfaceAverager->CalculateFluxSurfaceAverage(ir, fluxGridType, F);
}
real_t RadialGrid::EvaluateFluxSurfaceIntegral(len_t ir, fluxGridType fluxGridType, std::function<real_t(real_t,real_t,real_t)> F){
    return fluxSurfaceAverager->EvaluateFluxSurfaceIntegral(ir, fluxGridType, F);
}

real_t RadialGrid::CalculatePXiBounceAverageAtP(len_t ir, real_t p, real_t xi0, fluxGridType fluxGridType, std::function<real_t(real_t,real_t,real_t,real_t)> F){
    return fluxSurfaceAverager->CalculatePXiBounceAverageAtP(ir,p,xi0,fluxGridType,F);
}
real_t RadialGrid::EvaluatePXiBounceIntegralAtP(len_t ir, real_t p, real_t xi0, fluxGridType fluxGridType, std::function<real_t(real_t,real_t,real_t,real_t)> F){
    return fluxSurfaceAverager->EvaluatePXiBounceIntegralAtP(ir,p,xi0,fluxGridType,F);
}



/**
 * Sets reference magnetic field quantities that have been
 * generated by a RadialGridGenerator (FluxSurfaceAverager
 * takes ownership of these and will deallocate them).
 */
void RadialGrid::SetReferenceMagneticFieldData(
    len_t ntheta_ref, real_t *theta_ref,
    real_t **B_ref, real_t **B_ref_f,
    real_t **Jacobian_ref, real_t **Jacobian_ref_f,
    real_t **ROverR0_ref ,real_t **ROverR0_ref_f, 
    real_t **NablaR2_ref, real_t **NablaR2_ref_f,
    real_t *Bmin, real_t *Bmin_f,
    real_t *Bmax, real_t *Bmax_f,
    real_t *BtorGOverR0, real_t *BtorGOverR0_f,
    real_t R0
){
    DeallocateMagneticData();

    this->Bmin           = Bmin;
    this->Bmin_f         = Bmin_f;
    this->Bmax           = Bmax;
    this->Bmax_f         = Bmax_f;
    this->BtorGOverR0    = BtorGOverR0;
    this->BtorGOverR0_f  = BtorGOverR0_f;
    this->R0             = R0;

    fluxSurfaceAverager->SetReferenceMagneticFieldData(
        ntheta_ref, theta_ref, B_ref, B_ref_f,
        Jacobian_ref, Jacobian_ref_f,
        ROverR0_ref , ROverR0_ref_f, 
        NablaR2_ref,  NablaR2_ref_f
    );
}



/**
 * Deallocators.
 */
void RadialGrid::DeallocateGrid() {
    if (this->r == nullptr)
        return;

    delete [] this->dr_f;
    delete [] this->dr;
    delete [] this->r_f;
    delete [] this->r;
}

void RadialGrid::RebuildFluxSurfaceAveragedQuantities(){
 real_t 
    *effectivePassingFraction   = nullptr, 
    *effectivePassingFraction_f = nullptr, 
    *FSA_B2   = nullptr,
    *FSA_B2_f = nullptr,
    *FSA_B    = nullptr,
    *FSA_B_f  = nullptr,
    *FSA_nablaR2OverR2   = nullptr,
    *FSA_nablaR2OverR2_f = nullptr, 
    *FSA_1OverR2   = nullptr,
    *FSA_1OverR2_f = nullptr;

    SetFluxSurfaceAverage(FSA_1OverR2,FSA_1OverR2_f, [](real_t , real_t ROverR0, real_t ){return 1/(ROverR0*ROverR0);} );
    SetFluxSurfaceAverage(FSA_B,FSA_B_f, [](real_t BOverBmin, real_t , real_t ){return BOverBmin;} );
    SetFluxSurfaceAverage(FSA_B2,FSA_B2_f, [](real_t BOverBmin, real_t , real_t ){return BOverBmin*BOverBmin;} );
    SetFluxSurfaceAverage(FSA_nablaR2OverR2,FSA_nablaR2OverR2_f, [](real_t , real_t ROverR0, real_t NablaR2){return NablaR2/(ROverR0*ROverR0);} );
    

    SetEffectivePassingFraction(effectivePassingFraction,effectivePassingFraction_f, FSA_B2, FSA_B2_f);


    InitializeFSAvg(effectivePassingFraction,effectivePassingFraction_f,
        FSA_B,FSA_B_f,FSA_B2,FSA_B2_f,FSA_1OverR2, FSA_1OverR2_f,FSA_nablaR2OverR2,FSA_nablaR2OverR2_f);

}


void RadialGrid::SetFluxSurfaceAverage(real_t *&FSA_quantity, real_t *&FSA_quantity_f, std::function<real_t(real_t,real_t,real_t)> F){
    FSA_quantity   = new real_t[GetNr()];
    FSA_quantity_f = new real_t[GetNr()+1];

    for(len_t ir=0; ir<nr; ir++){
        FSA_quantity[ir] = CalculateFluxSurfaceAverage(ir, FLUXGRIDTYPE_DISTRIBUTION, F);
    }

    
    for(len_t ir=0; ir<=nr; ir++){
        FSA_quantity_f[ir] = CalculateFluxSurfaceAverage(ir, FLUXGRIDTYPE_RADIAL, F);
    }
}


/**
 * The function is used in the evaluation of the effective passing fraction,
 * and represents x / <1-x B/Bmax>
 */
struct EPF_params {real_t BminOverBmax; len_t ir; RadialGrid *rGrid; fluxGridType fgType;};
real_t RadialGrid::effectivePassingFractionIntegrand(real_t x, void *p){
    struct EPF_params *params = (struct EPF_params *) p;
    RadialGrid *rGrid = params->rGrid;
    real_t BminOverBmax = params->BminOverBmax; 
    len_t ir = params->ir;
    fluxGridType fluxGridType = params->fgType;
    std::function<real_t(real_t,real_t,real_t)> fluxAvgFunc = [x,BminOverBmax](real_t BOverBmin,real_t, real_t){
        return sqrt(1 - x * BminOverBmax * BOverBmin );
    };
    return x/ rGrid->CalculateFluxSurfaceAverage(ir, fluxGridType, fluxAvgFunc);
}

void RadialGrid::SetEffectivePassingFraction(real_t *&EPF, real_t *&, real_t *FSA_B2, real_t*){
    gsl_integration_workspace *gsl_w = gsl_integration_workspace_alloc(1000);
    gsl_function EPF_func;
    EPF_params paramstruct;
    real_t EPF_integral;
    EPF = new real_t[GetNr()];
    real_t error = 0;
    for (len_t ir=0; ir<GetNr(); ir++){
        real_t Bmin = GetBmin(ir);
        real_t Bmax = GetBmax(ir);
        real_t BminOverBmax;
        if(Bmin==Bmax) // handles B(theta) = 0 case
            BminOverBmax = 1; 
        else
            BminOverBmax = Bmin/Bmax;
        paramstruct = {BminOverBmax,ir,this,FLUXGRIDTYPE_DISTRIBUTION};
        EPF_func.function = &(effectivePassingFractionIntegrand);
        EPF_func.params = &paramstruct;
        real_t epsabs = 0, epsrel = 1e-4, lim = gsl_w->limit;
        gsl_integration_qags(&EPF_func, 0,1,epsabs,epsrel,lim,gsl_w,&EPF_integral, &error);
        EPF[ir] = (3.0/4) * BminOverBmax*BminOverBmax*FSA_B2[ir] * EPF_integral;
    }
    gsl_integration_workspace_free(gsl_w);

}

void RadialGrid::InitializeFSAvg(
            real_t *epf, real_t *epf_f, real_t *Bavg, real_t *Bavg_f, 
            real_t *B2avg, real_t *B2avg_f,
            real_t *OneOverR2_avg, real_t *OneOverR2_avg_f,
            real_t *nablaR2OverR2_avg, real_t *nablaR2OverR2_avg_f)
{

    DeallocateFSAvg();
    this->effectivePassingFraction   = epf;
    this->effectivePassingFraction_f = epf_f;
    this->FSA_B                      = Bavg;
    this->FSA_B_f                    = Bavg_f;
    this->FSA_B2                     = B2avg;
    this->FSA_B2_f                   = B2avg_f;
    this->FSA_1OverR2                = OneOverR2_avg;
    this->FSA_1OverR2_f              = OneOverR2_avg_f;
    this->FSA_nablaR2OverR2          = nablaR2OverR2_avg;
    this->FSA_nablaR2OverR2_f        = nablaR2OverR2_avg_f;
    
    
}
void RadialGrid::DeallocateFSAvg(){
    if (this->effectivePassingFraction == nullptr)
        return;

    delete [] this->FSA_B;
    delete [] this->FSA_B_f;
    delete [] this->FSA_B2;
    delete [] this->FSA_B2_f;
    delete [] this->effectivePassingFraction;
    delete [] this->FSA_nablaR2OverR2;
    delete [] this->FSA_nablaR2OverR2_f;
    delete [] this->FSA_1OverR2;
    delete [] this->FSA_1OverR2_f;
}

