"""Plots the simulation result generated by `generateCylindrical.py`.

Visualizes the runaway distribution and knock-on source term in phase space,
as well as compares the resulting avalanche growth rate with fluid theory.
"""

from pathlib import Path
import sys

import matplotlib.pyplot as plt
import numpy as np

try:
    import DREAM
except ModuleNotFoundError:
    sys.path.append(str(Path(__file__).resolve().parents[2] / "py"))
    import DREAM

from DREAM.DREAMOutput import DREAMOutput

plt.rc("font", size=12)
plt.rc("lines", linewidth=2)

output = Path(__file__).absolute().parent / "outputCylindrical.h5"
if not output.exists():
    print(
        "Output file has not yet been created: "
        "run settingsCylindrical.h5 produced by generateCylindrical.py"
    )
    sys.exit(0)

do = DREAMOutput(output)

ir = 0
n_hot_re = do.eqsys.f_hot.partialDensity()[:, ir]
n_re_tot = do.eqsys.n_re.data[:, ir] + n_hot_re
Gamma = (n_re_tot[1:] - n_re_tot[:-1]) / (
    n_re_tot[1:] * (do.grid.t[1:] - do.grid.t[:-1])
)

plt.figure()
plt.plot(do.grid.t[1:], Gamma, "k", label="Boltzmann (numeric)")
plt.plot(
    do.grid.t[1:],
    do.other.fluid.GammaAva.data[:, ir],
    "--r",
    label=r"$\Gamma_\mathrm{ava}$ (theory)",
)
plt.xlim(0, 0.2)
plt.ylim(0, 17.5)
plt.xlabel("Time [s]")
plt.ylabel(r"$\Gamma$ [s$^{-1}$]")
plt.title("Avalanche growth rate")
plt.legend()

plt.figure()
do.eqsys.f_hot.plot(r=ir, t=range(0, do.grid.t.size, 5), show=False)
plt.xlim(0, 30)
plt.ylim(1e-11, 1e2)
plt.title("Distribution evolution")

plt.figure()
do.other.hottail.C_boltz.plot(
    coordinates="cyl", logarithmic=True, show=False, levels=np.linspace(-2, 5, 100)
)
plt.xlim(-1, 6)
plt.ylim(0, 5)
plt.axis("equal")

plt.show()
