"""
Plots the simulation result generated by `generateAdvanced.py`
and, optionally, by `generateToroidal.py`.

For full plot functionality:

$ python3 generateAdvanced.py
$ python3 generateToroidal.py
$ dreami settingsAdvanced.h5
$ dreami settingsToroidal.h5
$ python3 plotAdvanced.py

Plots the knock-on source term in toroidal geometry
and compares simulations where only a hot grid is used (RP externals)
and when a hot + re grid is used to kinetically resolve all runaways.
"""

from pathlib import Path
import sys

import matplotlib.pyplot as plt
import numpy as np

try:
    import DREAM
except ModuleNotFoundError:
    sys.path.append(str(Path(__file__).resolve().parents[2] / "py"))
    import DREAM

from DREAM.DREAMOutput import DREAMOutput

plt.rc("font", size=12)
plt.rc("lines", linewidth=2)

output = Path(__file__).absolute().parent / "outputAdvanced.h5"
if not output.exists():
    print(
        "Output file has not yet been created: "
        "run settingsAdvanced.h5 produced by generateAdvanced.py"
    )
    sys.exit(0)

output_toroidal = output.with_name("outputToroidal.h5")

do = DREAMOutput(output)
do2 = None
if output_toroidal.exists():
    do2 = DREAMOutput(output_toroidal)
else:
    print(
        "Warning: toroidal case not run. "
        "To compare with simple toroidal case, "
        "also run the case: generateToroidal.py"
    )

#########
# Compute avalanche growth rates including runaways on the hot grid
#########
ir = 0
n_hot_re = do.eqsys.f_hot.partialDensity()[:, ir]
n_re_tot = do.eqsys.f_re.moment(1)[:, ir] + n_hot_re
Gamma = (n_re_tot[1:] - n_re_tot[:-1]) / (
    n_re_tot[1:] * (do.grid.t[1:] - do.grid.t[:-1])
)

Gamma2 = None
if do2 is not None:
    n_hot_re2 = do2.eqsys.f_hot.partialDensity()[:, ir]
    n_re_tot2 = do2.eqsys.n_re.data[:, ir] + n_hot_re2
    Gamma2 = (n_re_tot2[1:] - n_re_tot2[:-1]) / (
        n_re_tot2[1:] * (do2.grid.t[1:] - do2.grid.t[:-1])
    )

plt.figure()
plt.plot(do.grid.t[1:], Gamma, "k", label="Boltzmann (hot + re)")
if Gamma2 is not None:
    plt.plot(do2.grid.t[1:], Gamma2, ":b", label="Boltzmann (hot + external)")
plt.plot(
    do.grid.t[1:],
    do.other.fluid.GammaAva.data[:, ir],
    "--r",
    label=r"$\Gamma_\mathrm{ava}$ (theory)",
)
plt.xlim(0, 0.5)
plt.ylim(0, 8)
plt.xlabel("Time [s]")
plt.ylabel(r"$\Gamma$ [s$^{-1}$]")
plt.title("Avalanche growth rate")
plt.legend()


plt.figure()
# hot distribution
ax = do.eqsys.f_hot.plot(r=ir, t=range(0, do.grid.t.size, 20), show=False)
do.eqsys.f_re.plot(r=ir, t=range(0, do.grid.t.size, 20), ax=ax, show=False)
plt.xlim(0, 240)
plt.ylim(1e-11, 1e-3)
plt.title("Distribution evolution")

plt.figure()
levels = np.linspace(-2, 3, 100)
ax, *__ = do.other.hottail.C_boltz.plot(
    r=ir, t=-1, coordinates="cyl", logarithmic=True, show=False, levels=levels
)
do.other.runaway.C_boltz.plot(
    r=ir, t=-1, coordinates="cyl", logarithmic=True, show=False, ax=ax, levels=levels
)
plt.axis("equal")
plt.xlim(-2, 7)
plt.ylim(0, 5)
plt.show(block=False)

plt.figure()
plt.semilogy(
    do.grid.hottail.p,
    do.other.hottail.C_boltz.angleAveraged()[-1, ir] / n_re_tot[-1],
    "k",
    label="hot+re (boltz)",
)
plt.semilogy(
    do.grid.runaway.p,
    do.other.runaway.C_boltz.angleAveraged()[-1, ir] / n_re_tot[-1],
    "k",
)
if do2 is not None:
    plt.semilogy(
        do2.grid.hottail.p,
        (
            do2.other.hottail.S_ava.angleAveraged()[-1, ir]
            + do2.other.hottail.C_boltz.angleAveraged()[-1, ir]
        )
        / n_re_tot2[-1],
        "--r",
        label="hot (total)",
    )
    plt.semilogy(
        do2.grid.hottail.p,
        do2.other.hottail.C_boltz.angleAveraged()[-1, ir] / n_re_tot2[-1],
        "--b",
        label="hot (boltz)",
    )
    plt.semilogy(
        do2.grid.hottail.p,
        do2.other.hottail.S_ava.angleAveraged()[-1, ir] / n_re_tot2[-1],
        ":b",
        label="hot (external RP)",
    )

plt.xlim(0, 30)
plt.ylim(1e-9, 1e4)
plt.xlabel("$p / m_e c$")
plt.ylabel(r"$\langle C_\mathrm{boltz}\rangle / n_\mathrm{RE}$")
plt.legend()
plt.title("Angle averaged knock-on source")

plt.show(block=True)
