/* This file was auto-generated by 'get_nist.py' on 2021-01-25 15:52:54 */

#include "DREAM/nistdata.h"

/* H */
const len_t H_binding_Z = 1;
const real_t H_binding_data[1] = {13.5984345997};
/* He */
const len_t He_binding_Z = 2;
const real_t He_binding_data[2] = {79.0051545000,54.4177654860};
/* Be */
const len_t Be_binding_Z = 4;
const real_t Be_binding_data[4] = {399.1486400000,389.8259500000,371.6147900000,217.7185861000};
/* Ne */
const len_t Ne_binding_Z = 10;
const real_t Ne_binding_data[10] = {3511.6960000000,3490.1320000000,3449.1680000000,3385.7440000000,3288.5540000000,3162.3070000000,3004.3740000000,2797.1040000000,2558.0070100000,1362.1991600000};
/* Ar */
const len_t Ar_binding_Z = 18;
const real_t Ar_binding_data[18] = {14400.8000000000,14385.0000000000,14357.4000000000,14316.7000000000,14257.1000000000,14182.2000000000,14090.9000000000,13966.6000000000,13823.1000000000,13400.5000000000,12920.8000000000,12380.3000000000,11761.3000000000,11075.9000000000,10320.7000000000,9465.2640000000,8546.8885000000,4426.2229000000};
const len_t nist_binding_n = 5;
struct nist_data nist_binding_table[5] = {
	{"H",H_binding_Z,H_binding_data},
	{"He",He_binding_Z,He_binding_data},
	{"Be",Be_binding_Z,Be_binding_data},
	{"Ne",Ne_binding_Z,Ne_binding_data},
	{"Ar",Ar_binding_Z,Ar_binding_data}
};
