/* This file was auto-generated by 'get_nist.py' on 2021-07-01 16:32:02 */

#include "DREAM/nistdata.h"

/* H */
const len_t H_binding_Z = 1;
const real_t H_binding_data[1] = {13.5984345997};
/* He */
const len_t He_binding_Z = 2;
const real_t He_binding_data[2] = {79.0051545000,54.4177654860};
/* Li */
const len_t Li_binding_Z = 3;
const real_t Li_binding_data[3] = {203.4861711000,198.0944562000,122.4543591400};
/* Be */
const len_t Be_binding_Z = 4;
const real_t Be_binding_data[4] = {399.1486400000,389.8259500000,371.6147900000,217.7185861000};
/* C */
const len_t C_binding_Z = 6;
const real_t C_binding_data[6] = {1030.1085000000,1018.8482000000,994.4650000000,946.5772400000,882.0837200000,489.9931980000};
/* O */
const len_t O_binding_Z = 8;
const real_t O_binding_data[8] = {2043.8428000000,2030.2248000000,1995.1036000000,1940.1681000000,1862.7546000000,1748.8556000000,1610.7367100000,871.4098830000};
/* Ne */
const len_t Ne_binding_Z = 10;
const real_t Ne_binding_data[10] = {3511.6960000000,3490.1320000000,3449.1680000000,3385.7440000000,3288.5540000000,3162.3070000000,3004.3740000000,2797.1040000000,2558.0070100000,1362.1991600000};
/* Ar */
const len_t Ar_binding_Z = 18;
const real_t Ar_binding_data[18] = {14400.8000000000,14385.0000000000,14357.4000000000,14316.7000000000,14257.1000000000,14182.2000000000,14090.9000000000,13966.6000000000,13823.1000000000,13400.5000000000,12920.8000000000,12380.3000000000,11761.3000000000,11075.9000000000,10320.7000000000,9465.2640000000,8546.8885000000,4426.2229000000};
const len_t nist_binding_n = 8;
struct nist_data nist_binding_table[8] = {
	{"H",H_binding_Z,H_binding_data},
	{"He",He_binding_Z,He_binding_data},
	{"Li",Li_binding_Z,Li_binding_data},
	{"Be",Be_binding_Z,Be_binding_data},
	{"C",C_binding_Z,C_binding_data},
	{"O",O_binding_Z,O_binding_data},
	{"Ne",Ne_binding_Z,Ne_binding_data},
	{"Ar",Ar_binding_Z,Ar_binding_data}
};
