/* This file was auto-generated by 'get_nist.py' on 2020-06-12 21:34:40 */

#include "DREAM/nistdata.h"

/* H */
const len_t H_ionization_Z = 1;
const real_t H_ionization_data[1] = {13.5984344900};
/* He */
const len_t He_ionization_Z = 2;
const real_t He_ionization_data[2] = {4.5873888000,54.4177650000};
/* Ar */
const len_t Ar_ionization_Z = 18;
const real_t Ar_ionization_data[17] = {5.7596110000,7.6296000000,40.7350000000,59.5800000000,74.8400000000,1.2900000000,124.4100000000,143.4567000000,422.6000000000,479.7600000000,540.4000000000,619.0000000000,685.5000000000,755.1300000000,855.5000000000,918.3750000000,4120.6656000000};
const len_t nist_ionization_n = 3;
struct nist_data nist_ionization_table[3] = {
	{"H",H_ionization_Z,H_ionization_data},
	{"He",He_ionization_Z,He_ionization_data},
	{"Ar",Ar_ionization_Z,Ar_ionization_data}
};
