/* This file was auto-generated by 'get_nist.py' on 2020-09-16 21:46:12 */

#include "DREAM/nistdata.h"

/* H */
const len_t H_ionization_Z = 1;
const real_t H_ionization_data[1] = {13.5984344900};
/* He */
const len_t He_ionization_Z = 2;
const real_t He_ionization_data[2] = {24.5873888000,54.4177650000};
/* Ne */
const len_t Ne_ionization_Z = 10;
const real_t Ne_ionization_data[10] = {21.5645400000,40.9629700000,63.4233000000,97.1900000000,126.2470000000,157.9340000000,207.2710000000,239.0970000000,1195.8078300000,1362.1991500000};
/* Ar */
const len_t Ar_ionization_Z = 18;
const real_t Ar_ionization_data[18] = {15.7596117000,27.6296700000,40.7350000000,59.5800000000,74.8400000000,91.2900000000,124.4100000000,143.4567000000,422.6000000000,479.7600000000,540.4000000000,619.0000000000,685.5000000000,755.1300000000,855.5000000000,918.3750000000,4120.6656000000,4426.2228000000};
const len_t nist_ionization_n = 4;
struct nist_data nist_ionization_table[4] = {
	{"H",H_ionization_Z,H_ionization_data},
	{"He",He_ionization_Z,He_ionization_data},
	{"Ne",Ne_ionization_Z,Ne_ionization_data},
	{"Ar",Ar_ionization_Z,Ar_ionization_data}
};
