/* This file was auto-generated by 'get_nist.py' on 2020-06-13 10:30:32 */

#include "DREAM/nistdata.h"

/* H */
const len_t H_binding_Z = 1;
const real_t H_binding_data[1] = {13.5984344900};
/* He */
const len_t He_binding_Z = 2;
const real_t He_binding_data[2] = {79.0051538000,54.4177650000};
/* Ar */
const len_t Ar_binding_Z = 18;
const real_t Ar_binding_data[18] = {14400.8000000000,14385.0000000000,14357.4000000000,14316.7000000000,14257.1000000000,14182.2000000000,14090.9000000000,13966.6000000000,13823.1000000000,13400.5000000000,12920.8000000000,12380.3000000000,11761.3000000000,11075.9000000000,10320.7000000000,9465.2640000000,8546.8885000000,4426.2228000000};
const len_t nist_binding_n = 3;
struct nist_data nist_binding_table[3] = {
	{"H",H_binding_Z,H_binding_data},
	{"He",He_binding_Z,He_binding_data},
	{"Ar",Ar_binding_Z,Ar_binding_data}
};
