# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.cbElements = QtWidgets.QComboBox(self.centralwidget)
        self.cbElements.setObjectName("cbElements")
        self.verticalLayout.addWidget(self.cbElements)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.tbTe = QtWidgets.QLineEdit(self.centralwidget)
        self.tbTe.setObjectName("tbTe")
        self.horizontalLayout_2.addWidget(self.tbTe)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.tbNe = QtWidgets.QLineEdit(self.centralwidget)
        self.tbNe.setObjectName("tbNe")
        self.horizontalLayout_2.addWidget(self.tbNe)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.btnCalc = QtWidgets.QPushButton(self.centralwidget)
        self.btnCalc.setObjectName("btnCalc")
        self.verticalLayout.addWidget(self.btnCalc)
        self.verticalLayout.setStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Charge State Distribution Solver"))
        self.label.setText(_translate("MainWindow", "Element"))
        self.label_4.setText(_translate("MainWindow", "Electron temperature:"))
        self.tbTe.setText(_translate("MainWindow", "5"))
        self.label_7.setText(_translate("MainWindow", "eV   "))
        self.label_2.setText(_translate("MainWindow", "Electron density:"))
        self.tbNe.setText(_translate("MainWindow", "1e19"))
        self.label_6.setText(_translate("MainWindow", "m^-3"))
        self.btnCalc.setText(_translate("MainWindow", "Evaluate"))
