
#!/usr/bin/env python3

import argparse
import datetime
import pathlib
import data
import numpy as np


def cpp_array(realtype, name, values):
      s = f"const {realtype} {name}[{len(values)}] = {{"
      s += ",".join(f"{float(v):.12e}" for v in values)
      s += "};\n"
      return s


def amjuel_eval(coeff, n, T, nT=9, nn=9):
      n_eval = min(max(n, 1e14), 1e22)
      logn = np.log(n_eval * 1e-14)   # n / 1e14 = n[m^-3] / (1e8 cm^-3)
      logT = np.log(T)

      s = 0.0
      pT = 1.0
      for iT in range(nT):
          pn = 1.0
          for in_ in range(nn):
              s += coeff[iT*nn + in_] * pT * pn
              pn *= logn
          pT *= logT

      return np.exp(s) * 1e-6         # cm^3/s -> m^3/s


def constant_eval(value, n, T):
      return value


def zero_eval(n, T):
      return 0.0

def build_rate_table(reaction, n_grid, T_grid):
      dtype = reaction["data_type"]
      raw = reaction["data"]

      values = []
      for T in T_grid:
            for n in n_grid:
          
              if dtype in ("TODO", "FORMULA", "UNCLEAR"):
                  v = zero_eval(n, T)

              elif dtype == "CONSTANT":
                  v = constant_eval(raw, n, T)

              elif dtype in ("AMJUEL", "AMJUEL_POLYNOMIAL"):
                  coeff = getattr(data, raw["coefficients"])
                  v = amjuel_eval(
                      coeff,
                      n,
                      T,
                      raw.get("n_temperature", 9),
                      raw.get("n_density", 9)
                  )

              elif dtype == "ENERGY_INTERPOLATE":
                  # For now: placeholder zero until you decide the physics conversion.
                  # Later this becomes cross-section -> <sigma v>(n,T).
                  v = zero_eval(n, T)

              else:
                  raise ValueError(f"Unknown data_type '{dtype}' for {reaction['name']}")

              values.append(v)

      return values


def compile_molecular_rates(outputfile, inttype="len_t", realtype="real_t"):
      n_grid = np.logspace(14, 22, 50)   # m^-3
      T_grid = np.logspace(0, 4, 80)     # eV

      logn = np.log10(n_grid)
      logT = np.log10(T_grid)

      body = ""
      table = (f"const {inttype} molecular_rate_n = {len(data.MOLECULAR_REACTIONS)};\n"f"struct molecular_rate molecular_rate_table[{len(data.MOLECULAR_REACTIONS)}] ={{\n"
      )

      body += f"const {inttype} molecular_rate_nn = {len(n_grid)};\n"
      body += f"const {inttype} molecular_rate_nT = {len(T_grid)};\n"
      body += cpp_array(realtype, "molecular_rate_logn", logn)
      body += cpp_array(realtype, "molecular_rate_logT", logT)

      for reaction in data.MOLECULAR_REACTIONS:
          name = reaction["name"]
          cname = name.replace("+", "p").replace("-", "m").replace(".", "_")

          coeff_name = f"{cname}_coeff"
          coeff = build_rate_table(reaction, n_grid, T_grid)

          body += f"\n/* {name} */\n"
          body += cpp_array(realtype, coeff_name, coeff)

          table += (
              f'    {{"{name}", molecular_rate_nn, molecular_rate_nT, '
              f"molecular_rate_logn, molecular_rate_logT, {coeff_name}}},\n"
          )

      table += "};\n"

      filecontents = (
          "/* This file was auto-generated by 'generate_molecular_rates.py' "
          f"on {datetime.datetime.now().isoformat(sep=' ', timespec='seconds')} */\n\n"
          '#include "DREAM/MolecularRateData.hpp"\n\n'
          "namespace DREAM {\n\n"
          + body
          + "\n"
          + table
          + "\n}\n"
      )

      pathlib.Path(outputfile).parent.mkdir(parents=True, exist_ok=True)
      pathlib.Path(outputfile).write_text(filecontents)



def main():
      root = pathlib.Path(__file__).resolve().parents[2]
      outputfile = root / "src/MolecularRateData.cpp"
      compile_molecular_rates(outputfile)


if __name__ == "__main__":
      main()